#!/usr/bin/env bash
# This will configures  server to be listening on port 80 of all servers active IPv4 IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
